# Site settings
title: Ron Forbes
email: ronforbes528@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The personal website of Ron Forbes
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ronforbes.me" # the base hostname & protocol for your site
twitter_username: ronforbes
github_username:  ronforbes

# Build settings
markdown: kramdown
